version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "IdeaNoteApp-stg"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-ce5b49q07nro"
s3_prefix = "IdeaNoteApp-stg"
region = "ap-northeast-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Env=\"stg\""
image_repositories = []
confirm_changeset = true
