swagger: '2.0'

# モックのメタデータを記述する
info:
  description: |
    アイディアノートアプリのAPI
  version: 1.0.0
  title: IdeaNote
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html

# モックサーバーのプロトコルの選択
schemes:
- http

# エンドポイントの記述
paths:
  /themes:
    # テーマリスト取得API
    get:
      tags:
        - theme
      summary: テーマリスト取得
      description: テーマリストを返却します
      produces:
      - application/json
      responses:
        200:
          description: successful operation
          schema:
            $ref: '#/definitions/Themes'
    # テーマ登録API
    post:
      tags:
        - theme
      summary: テーマを追加
      description: テーマを追加
      parameters:
      - name: title
        in: path
        description: タイトル
        required: true
        type: string
      produces:
      - application/json
      responses:
        200:
          description: successful operation
          schema:
            $ref: '#/definitions/theme'
        400:
          description: Invalid ID supplied
        404:
          description: Pet not found
  /themes/{theme_id}/comments:
    # コメントリスト取得API
    get:
      tags:
      - comment
      summary: テーマに紐づくコメントリストを取得
      description: テーマに紐づくコメントリストを取得
      operationId: getPetById
      produces:
      - application/json
      responses:
        200:
          description: successful operation
          schema:
            $ref: '#/definitions/Comments'
        400:
          description: Invalid ID supplied
        404:
          description: Pet not found
    # コメント登録API
    post:
      tags:
      - comment
      summary: コメントを追加
      description: コメントを追加
      parameters:
      - name: comment
        in: path
        description: コメント
        required: true
        type: string
      produces:
      - application/json
      responses:
        200:
          description: successful operation
          schema:
            $ref: '#/definitions/Comment'
        400:
          description: Invalid ID supplied
        404:
          description: Pet not found
  /themes/{theme_id}/comments/{comment_id}:
    # コメント更新API
    put:
      tags:
      - comment
      summary: コメントを更新
      description: コメントを更新
      parameters:
      - name: comment
        in: path
        description: コメント
        required: true
        type: string
      produces:
      - application/json
      responses:
        200:
          description: successful operation
          schema:
            $ref: '#/definitions/Comment'
        400:
          description: Invalid ID supplied
        404:
          description: Pet not found
    # コメント削除API
    delete:
      tags:
      - comment
      summary: コメントを削除
      description: コメントを削除
      produces:
      - application/json
      responses:
        200:
          description: successful operation
        400:
          description: Invalid ID supplied
        404:
          description: Pet not found

# モデル定義の記述
definitions:
  Comments: 
    type: array
    items:
      properties: 
        id:
          type: integer
        theme_id:
          type: integer
        comment:
          type: string
  Comment:
    type: object
    properties:
      id:
        type: integer
      theme_id:
        type: integer
      comment:
        type: string
  Themes:
    type: array
    items:
      properties:
        id:
          type: integer
        title:
          type: string
  Theme:
    type: object
    properties:
      id:
        type: integer
      title:
        type: string
