name: Label pull_request
on:
  pull_request:
    types:
      - reopened
      - opened
jobs:
  label_pull_request:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Print branch name
        env:
          BRANCH_NAME: ${{ steps.extract_branch.outputs.branch }}
        run: echo $BRANCH_NAME
      - uses: actions/github-script@v6
        with:
          script: |
            const prNumber = context.payload.pull_request.number;
            const labelsToAdd = ['label1', 'label2']; // 追加するラベルを指定する
            const prefix = $BRANCH_NAME.split(':')[0];
            console.log('get branch name is ' + $BRANCH_NAME);
            console.log('prefix is ' + prefix);

            switch (prefix){
              case 'feature':
                const label = 'enhancement';
                break;
              case 'fix':
                const label = 'bug';
                break;
              case default:
                return;
                break;
            }

            await github.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: prNumber,
              labels: label
            });
