name: Label pull_request
on:
  pull_request:
    types:
      - reopened
      - opened
jobs:
  label_pull_request:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            const prNumber = context.payload.pull_request.number;
            const labelsToAdd = ['label1', 'label2']; // 追加するラベルを指定する
            const prefix = $BRANCH_NAME.split(':')[0];
            console.log('get branch name is ' + $({ github.event.pull_request.title });
            console.log('prefix is ' + prefix);

            switch (prefix){
              case 'feature':
                const setting_label = 'enhancement';
                break;
              case 'fix':
                const setting_label = 'bug';
                break;
              case default:
                return;
            }

            await github.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: prNumber,
              labels: setting_label
            });
