name: Label pull_request
on:
  pull_request:
    types:
      - reopened
      - opened
jobs:
  label_pull_request:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            const prNumber = context.payload.pull_request.number;


            await github.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: prNumber,
              labels: ['bug']
            });
